---
- hosts: all
  become: yes
  tasks:
  - name: Install apache
    apt:
      name: apache2
      state: present
  - name: Start service apache2, if not running
    service:
      name: apache2
      state: started
      enabled: yes
  - name: Put new index.html file
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
      owner: root
      group: www-data
      mode: 0644
